### ISSUE TITLE
Any ideas on how to show (/persist?) selection on the menu much appreciated!

### ISSUE THREAD

**Issue by jackherizsmith** [fac19/snake#33]

**Comment by bobbysebolao** [comment]
Hi @jackherizsmith , what do you mean? Please could you provide a bit more detail? 🙏

**Comment by jackherizsmith** [comment]
@bobbysebolao we have two characters and three difficult levels, and would like to have users select one of each before clicking go.

**Comment by Ivo-Evans** [comment]
Maybe you could use some state to determine whether to apply a CSS class to them or something

**Comment by bobbysebolao** [comment]
Sounds like a good idea @Ivo-Evans ! If you want to prevent the game `start()` function from being called until the character and difficulty have both been set, I'd suggest initialising both the `character` and `difficulty` states with a falsy value like `null` that will make it easy to check whether they have been set. You could check this with a ternary inside the click event that fires on line 25 of `characterSelector.js`:

```
      <a href="#" className="difficulty" onClick={character && difficulty ? startGame : doSomethingElse}>GO</a>
```
