### ISSUE TITLE
Importing components/utils from index files

### ISSUE THREAD

**Issue by bobbysebolao** [fac19/snake#34]
At the top of App.js:
```
import React, { useState, useEffect } from 'react'
import Score from './components/score'
import Snake from './components/snake'
import Food from './components/food'
import CharacterSelector from './components/characterSelector'
import getRandomCoordinates from './utils/getRandomCoordinates'
import initialState from './utils/initialState'
import onKeydown from './utils/keyDown'
import getGif from './utils/getSnake'
import useInterval from './utils/useInterval'
```

one thing you might like to try as your app increases in complexity is to import all of the components and utils that you need from an `index.js` file (instead of importing them from the individual component/util files). When you start having more components/utils, using index files can help keep things easy to read in `App.js`.

E.g. if you were to use this file structure to organise your components, you'd create an `index.js` file in your `components` folder, from which you'd export an object containing all your components from it:

**components/index.js**
```
import CharacterSelector from './characterSelector';
import Food from './food';
import Score from './score';
import Snake from './snake';

export { CharacterSelector, Food, Score, Snake };

```

You'd import this index file in `App.js`, and use [ES6 object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) to unpack the components from it (exactly the same as you've done to access the `useState` and `useEffect` methods from the `React` object):

```
import React, { useState, useEffect } from 'react'
import { CharacterSelector, Food, Score, Snake } from './components/index'
```

(hope this reads clearly, but if it doesn't than do give me a shout!)

**Comment by jackherizsmith** [comment]
@bobbysebolao thanks so much!
